#!/bin/bash

for f in *.{jpg,JPG,png,PNG,jpeg,JPEG}; do
	type=$(file "$f" | grep -oP '\w+(?= image data)')
	case $type in
		PNG) newExt=png;;
		JPEG) newExt=jpg;;
		*) echo "Unknown format of $f"; continue;;
	esac
	ext=${f##*.}
	if [[ $ext != $newExt ]]; then
		mv "$f" "${f%.*}.$newExt"
	fi
done
